name: Tofu

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'OpenTofu action to perform'
        required: true
        default: 'apply'
        type: choice
        options:
          - plan
          - apply
          - destroy
  push:
    branches: ['**']
    paths:
      - 'tofu/**'
  pull_request:
    branches: ['**']
    paths:
      - 'tofu/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

permissions:
  id-token: write
  contents: read
  pull-requests: write
  actions: write

jobs:
  deploy-infra:
    uses: nelsong6/pipeline-templates/.github/workflows/tofu-prod-template.yml@main
    with:
      action: ${{ github.event.inputs.action || 'apply' }}
    secrets: inherit
