name: Phase 1 - CI Build

permissions:
  contents: read
  packages: write

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-pipeline:
    uses: nelsong6/pipeline-templates/.github/workflows/container-app-build-template.yml@main
    with:
      node_version: '20'
    secrets: inherit
