name: Deploy Backend API

on:
  push:
    branches: [ main ]
    paths:
      - 'backend/**'
      - '.github/workflows/deploy-backend.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'backend/**'
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
  packages: write  # 🚀 ADDED: Required to push to GHCR
  pull-requests: write

env:
  WORKING_DIR: './backend'
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}/workout-api

jobs:
  build-and-deploy:
    name: Build and Deploy Backend
    runs-on: ubuntu-latest
    environment: prod
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    # ----------------------------------------------------------------
    # Infrastructure Context
    # ----------------------------------------------------------------
    - name: Setup OpenTofu
      uses: opentofu/setup-opentofu@v1
      with:
        tofu_version: 'latest'

    - name: Azure Login via OIDC
      uses: azure/login@v1
      with:
        client-id: 043b35c3-f5de-4578-acd2-8b8f4c78f461
        tenant-id: 2236b5e4-81d2-4d82-bde5-17b1037999ea
        subscription-id: aee0cbd2-8074-4001-b610-0f8edb4eaa3c

    - name: Get Infrastructure Outputs
      id: infra
      working-directory: ./tofu
      env:
        ARM_USE_OIDC: true
        ARM_CLIENT_ID: 043b35c3-f5de-4578-acd2-8b8f4c78f461
        ARM_TENANT_ID: 2236b5e4-81d2-4d82-bde5-17b1037999ea
        ARM_SUBSCRIPTION_ID: aee0cbd2-8074-4001-b610-0f8edb4eaa3c
      run: |
        tofu init
        
        echo "CONTAINER_APP_NAME=$(tofu output -raw container_app_name)" >> $GITHUB_OUTPUT
        echo "RESOURCE_GROUP_NAME=$(tofu output -raw resource_group_name)" >> $GITHUB_OUTPUT

    # ----------------------------------------------------------------
    # 🚀 Build and Push to GitHub Container Registry
    # ----------------------------------------------------------------
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        tags: |
          # Just use standard SHA tag (e.g., sha-0a55f40)
          type=sha
          # Branch tags (e.g., main, feature-x)
          type=ref,event=branch
          # PR tags (e.g., pr-6)
          type=ref,event=pr
          # Latest tag (only on default branch)
          type=raw,value=latest,enable={{is_default_branch}}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: ${{ env.WORKING_DIR }}
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}

    # ----------------------------------------------------------------
    # Deploy to Container Apps
    # ----------------------------------------------------------------
    - name: Deploy to Container App
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      run: |
        az containerapp update \
          --name ${{ steps.infra.outputs.CONTAINER_APP_NAME }} \
          --resource-group ${{ steps.infra.outputs.RESOURCE_GROUP_NAME }} \
          --image ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest

    - name: Get Container App URL
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      id: app-url
      run: |
        FQDN=$(az containerapp show \
          --name ${{ steps.infra.outputs.CONTAINER_APP_NAME }} \
          --resource-group ${{ steps.infra.outputs.RESOURCE_GROUP_NAME }} \
          --query "properties.configuration.ingress.fqdn" -o tsv)
        echo "url=https://$FQDN" >> $GITHUB_OUTPUT
        
        echo "### 🚀 Backend API Deployed!" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "**Registry:** GitHub Container Registry (GHCR)" >> $GITHUB_STEP_SUMMARY
        echo "**Image:** \`${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest\`" >> $GITHUB_STEP_SUMMARY
        echo "**API URL:** https://$FQDN" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "**Health Check:** https://$FQDN/health" >> $GITHUB_STEP_SUMMARY

    - name: Comment PR with deployment info
      if: github.event_name == 'pull_request'
      uses: actions/github-script@v7
      with:
        script: |
          const body = '### 🐳 Backend Container Built\n\n' +
                      '**Registry:** GitHub Container Registry (GHCR)\n' +
                      '**Image:** `${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}`\n\n' +
                      'Container built successfully. Will be deployed when merged to main.';
          
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: body
          });

  # Optional: Test the backend
  test:
    name: Test Backend
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: backend/package.json

    - name: Install dependencies
      working-directory: ./backend
      run: npm ci

    - name: Run linter
      working-directory: ./backend
      run: npm run lint || echo "No linter configured"

    - name: Run tests
      working-directory: ./backend
      run: npm test || echo "No tests configured yet"
