name: Consolidated Deployment

on:
  push:
    branches: ['**']
    # Removing paths entirely means this will trigger on ANY file change in the repo
  workflow_dispatch:
    inputs:
      run_infra:
        description: 'Deploy Infrastructure (OpenTofu)'
        required: true
        type: boolean
        default: true
      action:
        description: 'OpenTofu action (if running infra)'
        required: true
        default: 'apply'
        type: choice
        options:
          - plan
          - apply
          - destroy
      run_frontend:
        description: 'Deploy Frontend (Static Web App)'
        required: true
        type: boolean
        default: true
      run_backend:
        description: 'Deploy Backend (Container App)'
        required: true
        type: boolean
        default: true

concurrency:
  group: "master-deployment-lock"
  cancel-in-progress: false

permissions:
  id-token: write
  contents: write
  pull-requests: write
  actions: write
  packages: write

jobs:
  # ==========================================
  # 1. INFRASTRUCTURE
  # ==========================================
  deploy-infra:
    # Run on pushes, or if manually triggered and the checkbox is checked
    if: ${{ github.event_name == 'push' || inputs.run_infra }}
    uses: nelsong6/pipeline-templates/.github/workflows/tofu-deploy-template.yml@main
    with:
      action: ${{ inputs.action || 'apply' }}
    secrets: inherit

  # ==========================================
  # 2. FRONTEND (Runs parallel to Backend)
  # ==========================================
  deploy-frontend:
    name: Deploy Frontend
    needs: deploy-infra
    # Run if infra succeeded OR was deliberately skipped by the user,
    # AND we are not trying to 'destroy' the environment.
    if: |
      always() && 
      (needs.deploy-infra.result == 'success' || needs.deploy-infra.result == 'skipped') &&
      (github.event_name == 'push' || (inputs.run_frontend && inputs.action != 'destroy'))
    uses: nelsong6/pipeline-templates/.github/workflows/static-site-deploy.yml@main
    with:
      node_version: '20.x'
    secrets: inherit

  # ==========================================
  # 3. BACKEND (Runs parallel to Frontend)
  # ==========================================
  deploy-backend:
    name: Deploy Backend
    needs: deploy-infra
    # Run if infra succeeded OR was deliberately skipped by the user,
    # AND we are not trying to 'destroy' the environment.
    if: |
      always() && 
      (needs.deploy-infra.result == 'success' || needs.deploy-infra.result == 'skipped') &&
      (github.event_name == 'push' || (inputs.run_backend && inputs.action != 'destroy'))
    uses: nelsong6/pipeline-templates/.github/workflows/container-app-deploy-template.yml@main
    with:
      backend_directory: './backend'
      tofu_directory: './tofu'
      image_name_suffix: 'workout-api'
    secrets: inherit
