name: Phase 3 - CD Deploy

on:
  repository_dispatch:
    types: [spacelift_infra_ready]

permissions:
  id-token: write
  contents: read

jobs:
  call-deployment-template:
    uses: nelsong6/pipeline-templates/.github/workflows/full-stack-deploy-template.yml@main
    with:
      target_sha: ${{ github.event.client_payload.commit_sha }}
    secrets: inherit
