name: Production Deployment

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'OpenTofu action to perform'
        required: true
        default: 'apply'
        type: choice
        options:
          - plan
          - apply
          - destroy
  push:
    branches: ['main']
    paths:
      - 'tofu/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

permissions:
  id-token: write
  contents: write # Required for creating Git tags in the frontend deploy
  pull-requests: write
  actions: write
  packages: write # Required for GHCR push in the backend deploy

jobs:
  # 1. Deploy Infrastructure
  deploy-infra:
    # Points to your exact Tofu template filename
    uses: nelsong6/pipeline-templates/.github/workflows/tofu-prod-template.yml@main
    with:
      action: ${{ github.event.inputs.action || 'apply' }}
      environment: 'prod'
      working_directory: './tofu'
    secrets: inherit

  # 2. Deploy Frontend
  deploy-frontend:
    name: Deploy Frontend
    needs: deploy-infra
    if: ${{ github.event.inputs.action == 'apply' || github.event_name == 'push' }}
    # Points to your exact Static Site filename
    uses: nelsong6/pipeline-templates/.github/workflows/static-site-deploy.yml@main
    with:
      frontend_directory: './frontend'
      tofu_directory: './tofu'
      node_version: '20.x'
    secrets: inherit

  # 3. Deploy Backend
  deploy-backend:
    name: Deploy Backend
    needs: deploy-frontend
    if: ${{ github.event.inputs.action == 'apply' || github.event_name == 'push' }}
    # Points to your exact Container App filename
    uses: nelsong6/pipeline-templates/.github/workflows/container-app-deploy-template.yml@main
    with:
      backend_directory: './backend'
      tofu_directory: './tofu'
      image_name_suffix: 'workout-api'
    secrets: inherit
