name: Tofu PR Plan

on:
  pull_request:
    branches: ['**']
    paths:
      - 'tofu/**'
      - '.github/workflows/tofu-pr-plan.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pr-plan:
    uses: nelsong6/pipeline-templates/.github/workflows/tofu-pr-plan-template.yml@main
    with:
      working_directory: './tofu'
    secrets: inherit